# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wlach/svn/wvtrunk/wvtftp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wlach/svn/wvtrunk/wvtftp

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config /home/wlach/svn/wvtrunk/wvtftp/CPackConfig.cmake

# Special rule for the target package
package/fast: package

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config /home/wlach/svn/wvtrunk/wvtftp/CPackSourceConfig.cmake

# Special rule for the target package_source
package_source/fast: package_source

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)

# Special rule for the target test
test/fast: test

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wlach/svn/wvtrunk/wvtftp/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wlach/svn/wvtrunk/wvtftp/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named wvtftp

# Build rule for target.
wvtftp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wvtftp

# fast build rule for target.
wvtftp/fast:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/build

#=============================================================================
# Target rules for targets named wvtftpd

# Build rule for target.
wvtftpd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wvtftpd

# fast build rule for target.
wvtftpd/fast:
	$(MAKE) -f CMakeFiles/wvtftpd.dir/build.make CMakeFiles/wvtftpd.dir/build

#=============================================================================
# Target rules for targets named all.t

# Build rule for target.
all.t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all.t

# fast build rule for target.
all.t/fast:
	$(MAKE) -f t/CMakeFiles/all.t.dir/build.make t/CMakeFiles/all.t.dir/build

# target to build an object file
wvtftpbase.o:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpbase.o

# target to preprocess a source file
wvtftpbase.i:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpbase.i

# target to generate assembly for a file
wvtftpbase.s:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpbase.s

# target to build an object file
wvtftpd.o:
	$(MAKE) -f CMakeFiles/wvtftpd.dir/build.make CMakeFiles/wvtftpd.dir/wvtftpd.o

# target to preprocess a source file
wvtftpd.i:
	$(MAKE) -f CMakeFiles/wvtftpd.dir/build.make CMakeFiles/wvtftpd.dir/wvtftpd.i

# target to generate assembly for a file
wvtftpd.s:
	$(MAKE) -f CMakeFiles/wvtftpd.dir/build.make CMakeFiles/wvtftpd.dir/wvtftpd.s

# target to build an object file
wvtftpserver.o:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpserver.o

# target to preprocess a source file
wvtftpserver.i:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpserver.i

# target to generate assembly for a file
wvtftpserver.s:
	$(MAKE) -f CMakeFiles/wvtftp.dir/build.make CMakeFiles/wvtftp.dir/wvtftpserver.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... wvtftp"
	@echo "... wvtftpd"
	@echo "... wvtftpbase.o"
	@echo "... wvtftpbase.i"
	@echo "... wvtftpbase.s"
	@echo "... wvtftpd.o"
	@echo "... wvtftpd.i"
	@echo "... wvtftpd.s"
	@echo "... wvtftpserver.o"
	@echo "... wvtftpserver.i"
	@echo "... wvtftpserver.s"
	@echo "... all.t"
	@echo "... wvtftpbase.o"
	@echo "... wvtftpbase.i"
	@echo "... wvtftpbase.s"
	@echo "... wvtftpd.o"
	@echo "... wvtftpd.i"
	@echo "... wvtftpd.s"
	@echo "... wvtftpserver.o"
	@echo "... wvtftpserver.i"
	@echo "... wvtftpserver.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

