.TH WvTFTPd 8 "Mar 2007" "WvTFTPd"
.SH NAME
wvtftpd \- The world's fastest and most configurable TFTP Server
.SH SYNOPSIS
.B wvtftpd
.RB [ OPTIONS ]
.SH DESCRIPTION
.B wvtftp
is a blindingly fast and amazingly configurable Trivial File Transfer
Protocol (RFC 738) server.
.PP
When
.B wvtftpd
starts, it first loads its configuration from
.IR /etc/wvtftpd.conf ,
which contains basic information about which files you want transferred, who
should get those files, etc.
.SH OPTIONS
There are a number of options currently recognised by
.BR wvtftpd .
.TP
.B "\-V"
Prints the current
.B wvtftpd
version information and exits.
.TP
.B "\-q"
Decrease log level (can be used multiple times)
.TP
.B "\-v"
Increase log level (can be used multiple times)
.br
Use this option when reporting any bugs or problems with the program.
.TP
.B "\-d"
Fork into the background and return (implies -s)
.TP
.B "\-s"
Write log entries to syslog
.SH BUGS
Probably very few, but if you find any, please report them to us.  There is a
mailing list for discussion about
.BR wvtftpd .
and other 
.BR WvStreams
projects. If you are having problems, or have anything else to say, check out
the WvStreams mailing list at 
.I http://groups.google.com/group/wvstreams-devel
.SH FILES
.TP
.I /etc/wvtftpd.conf
Configuration file which contains account, passwords and delivery
information.  A sample file is included with the source.
.SH AUTHORS
Mark C\[^o]t\['e] for Net Integration Technologies Inc., as
part of the NetIntegrator project.
.SH "HOME PAGE"
.I http://alumnit.ca/wiki/?page=WvTftp
