.\" Worldvisions Weaver Software:
.\"   Copyright (C) 1997-2004 Net Integration Technologies, Inc.
.\"
.\" This library is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public
.\" License as published by the Free Software Foundation; either
.\" version 2.1 of the License, or (at your option) any later version.
.\"
.\" This library is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\"
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this library; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

.TH WvTFTPd 1 "Aug 2004" "WvTFTPd"

.SH NAME
wvtftpd \- The world's fastest and most configurable TFTP Server


.SH SYNOPSIS
.B wvtftpd

.SH DESCRIPTION
.B wvtftp
is a blindingly fast and amazingly configurable Trivial File Transfer
Protocol (RFC 738) server.
.PP
When
.B wvtftpd
starts, it first loads its configuration from
.IR /etc/wvtftpd.conf ,
which contains basic information about which files you want transferred, who
should get those files, etc.
.PP
.SH OPTIONS
There are only a couple of options currently recognised by
.BR wvtftpd .
.TP
.B "\-V"
Prints the current
.B wvtftpd
version information and exits.
.TP
.B "\-d"
Displays debug information for troubleshooting
.BR wvtftpd
.TP
.B "\-dd"
Displays a lot of debug information for troubleshooting
.BR wvtftpd.
Use this option when reporting any bugs or problems with the program.
.PP
.SH BUGS
Probably very few, but if you find any, please report them to us.  There is a
mailing list for discussion about
.BR wvtftpd 
and other 
.BR WvStreams
projects. If you are having problems, or have anything else to say, send email
with the body "SUBSCRIBE" to
.BR <wvstreams-dev-request@lists.nit.ca> .
.PP
.SH FILES
.TP
.IR /etc/wvtftpd.conf
Configuration file which contains account, passwords and delivery
information.  A sample file is included with the source.
.PP
.SH AUTHORS
Mark Cote for Net Integration Technologies Inc., as
part of the NetIntegrator project.
.PP
.SH FAQ
.TP
.BR http://open.nit.ca/wvtftpd
.PP
